### ISSUE TITLE
[BUG] After close DCS, the Bridge hangs and can't closed at all. Taskmanager can't close too.

### ISSUE THREAD

**Issue by Bigopus** [DCS-Skunkworks/DCSBIOSBridge#15]
**DCS-BIOS version**
Version currently used

**Hardware used**
Arduino/ESP32/...

**Setup**
Relevant information about the whole setup.

**Describe the bug**
A clear and concise description of what the bug is. *If* you have problems with a DCS-BIOS control then use the control's ID when mentioning it. Eg. ```FLAPS_SWITCH```, ```GEAR_LEVER```.

**Post your *.dcs-bios_settings file**
If applicable please post your settings file.

**To Reproduce**
1. Start DCSBIOSBridge
2. Start DCS
3. Start Mission
4. Click Arduino switch
5. See error

**Expected behavior**

**Screenshots**

**Comment by jdahlblom** [comment]
Can you please give more information. Step by step.

**Comment by jdahlblom** [comment]
What operating system?

**Comment by jdahlblom** [comment]
This works for me:
* Running DCS mission
* DCSBIOSBridge running, sending DCS-BIOS data to 2 serial ports
* Closed the DCS mission
* Successfully closed DCSBIOSBridge

**Comment by Bigopus** [comment]
Hi Jerker,

 

It's running with WIN10.
I start DCSBridge, Port 3 to 12

I start DCS and play

After close DCS, the DCSBridge window is dead and stopped working

I can't close DCSBridge normal

I can't stop any port, all Buttons dead

I can't stop DCSBridge with taskmanager

The window keeps still on the screen

 

But I can start a new working DCSBridge.

 

Michael

 

 

Von: Jerker Dahlblom ***@***.*** 
Gesendet: Mittwoch, 6. März 2024 10:42
An: DCS-Skunkworks/DCSBIOSBridge ***@***.***>
Cc: Bigopus ***@***.***>; Author ***@***.***>
Betreff: Re: [DCS-Skunkworks/DCSBIOSBridge] [BUG] After close DCS, the Bridge hangs and can't closed at all. Taskmanager can't close too. (Issue #15)

 

This works for me:

*	Running DCS mission
*	DCSBIOSBridge running, sending DCS-BIOS data to 2 serial ports
*	Closed the DCS mission
*	Successfully closed DCSBIOSBridge

**Comment by jdahlblom** [comment]
Do you have any entries in the error log?

**Comment by jdahlblom** [comment]
[DCSBIOSBridge_x64_1.0.6.zip](https://github.com/DCS-Skunkworks/DCSBIOSBridge/files/14510484/DCSBIOSBridge_x64_1.0.6.zip)

Try this, I couldn't find anything obvious but I did find things to improve. It seems to me some resource (socket, port, other) is left open and cannot be disposed of.

**Comment by jdahlblom** [comment]
Any new information on this?

**Comment by Bigopus** [comment]
when I play DCS for longer time, the bridge is hanging sometimes after close the DCS. One board, with a Mega 2560 is very busy with all the Intercom potis. This board loose connection immediately after seconds. I'm very confused at the moment. Will try to slow down the datas. 

Thank you for watching my problem. :)

Michael 

 

Von: Jerker Dahlblom ***@***.*** 
Gesendet: Montag, 11. März 2024 08:16
An: DCS-Skunkworks/DCSBIOSBridge ***@***.***>
Cc: Bigopus ***@***.***>; Author ***@***.***>
Betreff: Re: [DCS-Skunkworks/DCSBIOSBridge] [BUG] After close DCS, the Bridge hangs and can't closed at all. Taskmanager can't close too. (Issue #15)

 

Any new information on this?

**Comment by Bigopus** [comment]
further information. I lost ingame sometime an USB port. Bodnar boards are very sensitive against EMI. Anytime a port closed/crashed, the dcs-bios bridge has the behavior as described above.

**Comment by jdahlblom** [comment]
> further information. I lost ingame sometime an USB port. Bodnar boards are very sensitive against EMI. Anytime a port closed/crashed, the dcs-bios bridge has the behavior as described above.

Have you updated to the latest version?

**Comment by Bigopus** [comment]
Yes, now I used the last version and something is wrong. The Bodnar boards disconnect immediately after starting DCS. That wasn't the case with the previous version. On the other hand, the ports no longer restart when I reconnect all or some of them. This worked with the previous version. 

Von: Jerker Dahlblom ***@***.*** 
Gesendet: Donnerstag, 4. April 2024 08:09
An: DCS-Skunkworks/DCSBIOSBridge ***@***.***>
Cc: Bigopus ***@***.***>; Author ***@***.***>
Betreff: Re: [DCS-Skunkworks/DCSBIOSBridge] [BUG] After close DCS, the Bridge hangs and can't closed at all. Taskmanager can't close too. (Issue #15)

 

further information. I lost ingame sometime an USB port. Bodnar boards are very sensitive against EMI. Anytime a port closed/crashed, the dcs-bios bridge has the behavior as described above.

Have you updated to the latest version?

**Comment by jdahlblom** [comment]
The behavior when detecting serial port problems is different with this version. It will handle some problems in a structured manner instead of getting hung.
I really can't help any more with this. I have with my single UNO R3 done testing and added safeguards accordingly.
I suggest you use socat.

**Comment by charliefoxtwo** [comment]
Closing this as won't fix, this repository is no longer receiving updates.
