### ISSUE TITLE
[BUG] : Servo motor lags when using rotary encoder to move it

### ISSUE THREAD

**Issue by psjshep** [DCS-Skunkworks/DCSBIOSBridge#31]
**DCS-BIOS version**
1.1.4

**Hardware used**
Arduino Uno (official board)

**Setup**
- Arduino Uno -> COM6
- DCSBiosBridge V1.1.4 -> COM6 @ 250000 baud
- stepper motor (gnd, +5v, signal to pin 11) - this rotates the barrel in the ammo counter
- Rotary encoder (gnd, signal1->pin7, signal2->pin8)
- bf109 sketch for the left ammo counter (rotatry encoder allows manually adjusting the counter up & down)

**Describe the bug**
- When I use the rotary encoder to turn the ammo counter the stepper seems to go into slow motion & slowly turns no matter how fast I turn the encoder
- If I use the socat cmd file (connect-serial-port.cmd -> port 6), rotating the encoder instantly moves the stepper & as fast as needed
- I tried v1.1.3 of DCSBiosBridge - that seems to almost work, but rotating the encoder in the opposite direction occasionally moves the stepper the wrong way for a moment... but the slow-motion is now gone

Sketch :

#define DCSBIOS_IRQ_SERIAL
#include "C:\Dev\doc\Addresses.h"
int LeftPinionAnti = 7;
int LeftPinionClock = 8;
int LeftAmmoCounter = 11;
DcsBios::RotaryEncoder szkk3AmmoLeft("SZKK3_AMMO_LEFT", "-3200", "+3200", LeftPinionAnti, LeftPinionClock);
DcsBios::ServoOutput mg1310ShellCounter(Bf_109K_4_MG131_0_SHELL_COUNTER_A, LeftAmmoCounter, 544, 2200);
void setup() {
  DcsBios::setup();
}
void loop() {
  DcsBios::loop();
}

**Post your *.dcs-bios_settings file**
SerialPortV2{COM6|250000|None|8|One|None|0|0|False|True

**To Reproduce**
1. Start DCSBIOSBridge
2. Start DCS
3. Start Mission
4. Rotate rotary encoder
5. observe slow-motion movement of the stepper

**Expected behavior**
As soon as the encoder is rotated, the stepper should instantly move. Fast rotation should translate to quicker movement of the stepper

**Screenshots**
n/a

**Comment by psjshep** [comment]
correction - servo motor

**Comment by jdahlblom** [comment]
Alright, I'll have a look at this.

**Comment by jdahlblom** [comment]
Following discussion on Discord the issue was that there was a 50ms delay between sending DCS-BIOS commands. The default was lowered to 5ms and a new option where the user can change the value.
This fixed this issue.
